FROM mongo:5.0

COPY todo-dataset.json /todo-dataset.json
CMD mongoimport -u "your username" -p "yoyr password" --host mongodb -d jikupmap -c todos --type json --file /todo-dataset.json --jsonArray --authenticationDatabase admin